### ISSUE TITLE
Backward incompatibility in API functions in `0.0.8`

### ISSUE THREAD

**Issue by szhan** [astheeggeggs/lshmm#125]
The latest updates to the API functions are affecting `tskit` development tests [here](https://github.com/tskit-dev/tskit/issues/2962).

`tskit` uses the following API functions in `lshmm`:
* `forwards`
* `backwards`
* `viterbi`
* `path_ll`

The positional arguments have changed, because the updated API functions now take `num_alleles`, which is needed to scale mutation rates based on the number of distinct alleles per site.

The keyword arguments have changed. In particular, `p_mutation` is now `prob_mutation`, and `scale_mutation_based_on_n_alleles` is now `scale_mutation_rate`.

Also, `path_ll` has been renamed to `path_loglik`.

Modifications should be made to the `lshmm` API functions and the `tskit` test suite to resolve this issue.

**Comment by jeromekelleher** [comment]
We don't need to update this repo I think, just make the necessary changes to the tskit tests.

**Comment by szhan** [comment]
The `num_alleles` was causing problems in the tskit tests. It is no longer an argument in the API functions. But `ploidy` is now a required argument in the API functions, and the reference panel is a set of reference haplotypes (not genotypes as before).

**Comment by szhan** [comment]
I'll update the tskit test suite to use `0.0.7` instead.
