### ISSUE TITLE
If statement checking size of `recombination_rate` array

### ISSUE THREAD

**Issue by szhan** [astheeggeggs/lshmm#18]
Is this condition [here](https://github.com/astheeggeggs/lshmm/blob/9b15d8417e2856e13b28d59b4c8d078068fd8c0b/lshmm/api.py#L91C5-L91C5) in `check` [here](https://github.com/astheeggeggs/lshmm/blob/9b15d8417e2856e13b28d59b4c8d078068fd8c0b/lshmm/api.py#L51C5-L51C11) supposed to use `==` instead of `is not`?

```
# Ensure that the recombination probabilities is either a scalar or a vector of length m
    if recombination_rate.shape[0] is not m:
        raise ValueError(f"recombination_rate is not a vector of length m: {m}")
```

**Comment by jeromekelleher** [comment]
Good spot @szhan - that'll fail in weird ways with the current implementation

**Comment by szhan** [comment]
I don't think we need to check whether `reference_panel.shape[1] == reference_panel.shape[2]`, because it is not incorrect to have a reference panel containing only two samples (even though that is obviously useless in practice).

**Comment by szhan** [comment]
I misunderstand what it means to have a `reference_panel` with three dimension. So, please ignore the above statement.
