### ISSUE TITLE
Module has no __version__ attribute

### ISSUE THREAD

**Issue by jeromekelleher** [astheeggeggs/lshmm#21]
It's helpful to set an ``__version__`` attribute so users can programatically see what version they are using.

**Comment by astheeggeggs** [comment]
What's your preferred way of doing this? Seems like there are a bunch:
https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module

**Comment by jeromekelleher** [comment]
It's a mess all right. The way we've settled on for tskit packages is to use setuptools_scm, e.g. in [tszip](https://github.com/tskit-dev/tszip/blob/main/setup.py) where possible

https://pypi.org/project/setuptools-scm/
