### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by jeromekelleher** [astheeggeggs/lshmm#5]
It's not clear what the external API should be. Here's one option, we have a set of functions like
```python
lshmm.haploid.forwards
lshmm.haploid.backwards
lshmm.haploid.viterbi
# and 
lshmm.diploid.forwards
lshmm.diploid.backwards
lshmm.diploid.viterbi
```
What do you think @astheeggeggs?

**Comment by astheeggeggs** [comment]
That makes sense to me.

**Comment by jeromekelleher** [comment]
OK, so simplest way to do that is to have two files ``haploid.py`` and ``diploid.py``, each of which has those three functions.

Although, come to think of it, it could be annoying to have two different function with the same name.

What if we just had three functions and we determined the ploidy from the dimensions of the input haplotypes? That'd be nice.

**Comment by astheeggeggs** [comment]
I've added ls.y with wrappers to check and run relevant functions based on ploidy and have added tests.
