### ISSUE TITLE
Convert haplotypes to genotypes for query

### ISSUE THREAD

**Issue by szhan** [astheeggeggs/lshmm#56]
In PR #50, a function was added to convert haplotypes to genotypes for the reference panel. Here, a function is added to do the same but for a query. Also, `get_examples_pars` in `core.py` is updated to use this function to prepare both the reference panel and query for tests.

**Comment by astheeggeggs** [comment]
I see - presumably this is only used in the tests for the queries right? It wouldn't make sense to throw phase info away!

**Comment by szhan** [comment]
It's just used in the tests.

**Comment by szhan** [comment]
Also, the function names aren't very good right now.

**Comment by szhan** [comment]
This is just refactoring what is being done in the tests. Also, I thought the diploid LS HMM is meant to phase an unphased diploid query genome into a set of phased diploid reference genomes?

**Comment by astheeggeggs** [comment]
Yep, totally. What I was querying was why we'd need to map query from haplotypes (phased) to genotypes (unphased). In anything but the tests, they should be passed as genotypes (unphased), but it makes sense in the tests.

**Comment by szhan** [comment]
I've moved the function under `LSBase` as a class function. Maybe that should avoid confusing it as a commonly used utility function?

**Comment by szhan** [comment]
I'm reverting the move for now, because I think the function can be used outside of tests.
