### ISSUE TITLE
Remove msprime dependency

### ISSUE THREAD

**Issue by jeromekelleher** [astheeggeggs/lshmm#6]
We shouldn't need it.

Only dependencies should be numba and numpy.

**Comment by astheeggeggs** [comment]
Currently it's in there for the simulation of data (which are then sent to matrices). Would is make sense to save these matrices within the test dir and read them in with numpy.load instead? Or is this purely in setup.cfg?

**Comment by jeromekelleher** [comment]
That's for testing, only stuff that's required at runtime should be in ``setup.cfg``. You can depend on whatever for testing, doesn't matter.

**Comment by astheeggeggs** [comment]
ah, nice. Good to go then - will remove.

**Comment by astheeggeggs** [comment]
msprime dependency removed from setup.cfg, but tskit and msprime dependencies retained for the testing envs in nox.
